#!/bin/zsh
clear 
# averigua el directorio que aloja el script
SCRIPT=$(readlink -f $0);
dir=`dirname $SCRIPT`
bdir=$dir/../../build;
echo $bdir
if  ! test -d "$bdir" ; then
    mkdir -p "$bdir" 
fi
cd "$bdir"
echo --------------------------------------------------------------------------------
export CXX=g++
export CMAKE_GENERATOR=Ninja
cmake ..
echo --------------------------------------------------------------------------------

